### ISSUE TITLE
RPC call starknet_chainId does not return DEVNET

### ISSUE THREAD

**Issue by gregoryguillou** [Shard-Labs/starknet-devnet#146]
**Describe the bug**
RPC calls to `starknet_chainId` does not return `DEVNET` but `SN_GOERLI`.

**To Reproduce**
Call `starknet_chainId` with json rpc. From what I see, the reason is that the value returned is `DEFAULT_CHAIN_ID` from `starknet_devnet/general_config.py` that is imported from`cairo-lang` in `src/starkware/starknet/definitions/general_config.py` and`TESTNET`. 

**Expected behavior**
I would expect the returned value is `DEVNET` or something else so that, from the chain we can know what we are using.

**Devnet version**

- I am using Devnet version: 0.2.4
- [x] This happens with a dockerized Devnet (check the box if true).

**Comment by FabijanC** [comment]
- I think It has to be either `SN_GOERLI` or `SN_MAIN` because there are internal validations which expect it to be either of the two values (you can try by cloning devnet locally and modifying this line in general_config.py).
- This Starknet chain ID also affects the transaction signature used by accounts. So, signature generators would have to know this Devnet-specific value.
- Then again, if we consider that starknet-devnet's goal is to mock alpha-goerli, it's not completely pointless to have it use `SN_GOERLI` as its Starknet chain ID.
