### ISSUE TITLE
`call_contract` still requires `entry_point_selector`

### ISSUE THREAD

**Issue by unparalleled-js** [Shard-Labs/starknet-devnet#267]
**Describe the bug**

When using `call_contract` endpoint and leaving `entry_point_selector` as `None` (as `starknet.py` requires now),
you get an assertion error from this line: https://github.com/Shard-Labs/starknet-devnet/blob/master/starknet_devnet/contract_wrapper.py#L42

because it requires the `entry_point` to not be `None`.

**Not reproducible on alpha-goerli**

- [X] This issue is only present on Devnet and cannot be reproduced on alpha-goerli (check the box if true).

**To Reproduce**

1. ... Start devnet
2. ... Pass `entry_point_selector` `null`
   ...

**Expected behavior**

It could perhaps use the account one, hardcoded when it is not provided.

**Screenshots**
If applicable, add screenshots to help explain your problem. However, prefer providing copyable text.

**Devnet version**

- I am using Devnet version: 0.3
- [ ] This happens with a dockerized Devnet (check the box if true).
- This does not appear on the following Devnet version:

**System specifications**

- OS: macOS
- CPU:
- Memory:
- Python version:

**Comment by unparalleled-js** [comment]
When I attempt to provide an entry point, I get an error from this assertion: https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/services/api/gateway/transaction.py#L202-L204

**Comment by FabijanC** [comment]
Shouldn't there be an entrypoint selector when doing calls? I'm aware that for invokes the default is now `__execute__`, but for making a call, you still have to know which function you are calling, right? Since it's not done through an account.

**Comment by cptartur** [comment]
I believe the problem comes from trying to use `call_contract` endpoint with InvokeFunction object. As far as I understand, to have `entry_point_selector != None` you always have to use tx `version=0` or the request will fail otherwise.

Though cairo-lang introduced this new dataclass [CallFunction](https://github.com/starkware-libs/cairo-lang/blob/v0.10.0/src/starkware/starknet/services/api/feeder_gateway/request_objects.py#L14) to use with calls to `call_contract` instead and it doesn't require version, nonce, etc. at all. We're kinda currently using it in starknet.py when using new account contracts (tx version 1) and it seems to be working correctly with devnet.
