### ISSUE TITLE
Support non-latest blocks

### ISSUE THREAD

**Issue by fracek** [Shard-Labs/starknet-devnet#388]
At the moment, the JSON-RPC API will return an error if block id is something different from the latest block. For integrating with dojo (and other use cases tbh) it would be nice to be able to use any (past) block number and hash.

**Comment by FabijanC** [comment]
Hi, thanks for the proposal! This is something I've been thinking about lately, but my concerns regard the memory consumption and if it would increase significantly. Because if we were to support this, we would need to copy and preserve every past state. Then again, it could be an optional feature.

**Comment by mikiw** [comment]
Related links:
https://ethereum.stackexchange.com/questions/91938/how-can-i-get-contract-data-from-certain-block
https://stackoverflow.com/questions/71275466/how-to-access-the-data-from-the-previous-block-of-ethereum-block-chain-through-t
https://www.reddit.com/r/ethdev/comments/s8fcr8/how_to_make_a_contract_view_call_to_an_older_block/

**Comment by FabijanC** [comment]
Actually just remembered, this issue seems to be requesting for JSON-RPC what has already been requested here: https://github.com/Shard-Labs/starknet-devnet/issues/155. So I would say that this #388 is a candidate for closing.

**Comment by fracek** [comment]
Sorry I didn't see #155. Good point about memory consumption.

**Comment by FabijanC** [comment]
Since the conversation seems to have kicked-off here, I'll close the older issue and copy its only message here:
> As noted in the disclaimer: https://github.com/Shard-Labs/starknet-devnet/#disclaimer currently all interaction is done with the latest block.
Can we support older blocks? If not, warning/error could be thrown.

I'll also rename this issue to strip the mention of JSON-RPC API.

This task can be prioritized after we're done dealing with our current tasks (although our next big task will be adapting to StarkNet 0.11, but we'll see).
