### ISSUE TITLE
Sample HTTP request for successful setup

### ISSUE THREAD

**Issue by rootulp** [Shard-Labs/starknet-devnet#93]
I'm trying to run a starknet devnet node to test [caigo](https://github.com/dontpanicdao/caigo). However, I'm observing that it is difficult to determine if my devnet node is running correctly.

I'm able to confirm that it's running via `docker ps` and I observe `404s` in logs when I try to make basic requests to my node

```sh
curl -X GET http://localhost:5000/get_block_number
```

But it would be helpful if there was a sample query in the README after [this step](https://github.com/Shard-Labs/starknet-devnet#run-with-docker=) to confirm the setup process was successful

**Comment by FabijanC** [comment]
Hi, thanks for the suggestion, I'll update the docs with an example.

A few notes:
- Devnet aims to mimic alpha-goerli testnet (available at https://alpha4.starknet.io/feeder_gateway/)
- There is no endpoint `/get_block_number`, the most similar is `/get_block`, and it is actually not at root, but at `/feeder_gateway`, so `/feeder_gateway/get_block`.
- You can test if Devnet is alive by executing `curl http://localhost:5000/is_alive` (omitting the request type defaults to GET).
- The behavior of `localhost` is sometimes different on mac, so you can try curling `127.0.0.1` instead of `localhost` (if that is the address you used with `docker run -p <ADDRESS>`

**Comment by rootulp** [comment]
Thanks @FabijanC ! I was able to start the starknet_devnet node and confirm it is serving requests via 

```
docker run -p 127.0.0.1:5000:5000 shardlabs/starknet-devnet

# In a separate terminal
curl http://127.0.0.1:5000/is_alive
```
